### ISSUE TITLE
Cannot find name 'Croppie'.

### ISSUE THREAD

**Issue by jpradeep2003** [deej81/ngx-croppie#2] opened 2017-07-30 04:55 UTC
I am getting the following compilation error:

```
[04:49:45]  typescript: node_modules/ngx-croppie/src/ngx-croppie.component.ts, line: 12
            Cannot find name 'CroppieOptions'.

      L11:  @ViewChild('imageEdit') imageEdit: ElementRef;
      L12:  @Input() croppieOptions: CroppieOptions;
      L13:  @Input() imageUrl: string;

            Cannot find name 'Croppie'.

      L17:      private _croppie: Croppie;
[04:49:45]  typescript: node_modules/ngx-croppie/src/ngx-croppie.component.ts, line: 17

```
I am using following dependencies in package.json:
```
    "croppie": "^2.5.0",
    "ngx-croppie": "^0.1.2",

```

**Comment by deej81** [comment] 2017-10-06 10:00
sorry for the massive amount of time it's taken to reply, work is mad right now!

I've investigated briefly and can't reproduce this issue I'm afraid. I've checked the example app https://github.com/deej81/ngx-croppie-example and it appears to be building fine, I've set it CI on it to keep an eye on the status. If I don't hear back in a week or so I'll assume you've long since moved on from my poor levels of support and close this issue. 

Sorry again.

**Closed** 2017-10-09 11:28 UTC
