### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_1_croppie___default.a is not a constructor

### ISSUE THREAD

**Issue by mikael-brochu** [deej81/ngx-croppie#6] opened 2018-03-26 15:05 UTC
Hi,

I tried using the component inside my angular project, however I keep getting the error:
`__WEBPACK_IMPORTED_MODULE_1_croppie___default.a is not a constructor`.

It seems to come from ngx-croppie.component.js when creating a `new Croppie`

**Comment by deej81** [comment] 2018-03-26 15:09
Hi, the issue is linked to this https://github.com/deej81/ngx-croppie/issues/5 . For now if you can you can work around by using the previous version of croppie (2.5.1) I believe.

**Comment by deej81** [comment] 2018-04-13 12:49
resolved in 1.0.0 although this release won't support older versions as the fix is pretty horrible

**Closed** 2018-04-15 08:27 UTC
